### ISSUE TITLE
(Suggestion) Add more documentation in the ReadME file

### ISSUE THREAD

**Issue by danrevah** [google/lintush#2]
It was a bit not clear what exactly this cli provides, and I had to install it to figure it out. 

I'd suggest to use https://github.com/faressoft/terminalizer to record it's main features and add this to the ReadMe file.

Great Readme files = More people are actually going to download & use it.
If you need any help with that, let me know..

**Comment by segevofer** [comment]
![demo](https://user-images.githubusercontent.com/4939021/71554157-4ef3a100-2a24-11ea-97a5-bdc2a15292ea.gif)
